#!/usr/bin/env bash
#
# 2015, j.grassler@syseleven.de
#
# Checks whether an openstack instance can be spawned

# Directory for all state related to sensu checks

lockdir=/tmp/check_instance_boot.lock
if mkdir "$lockdir"; then
  #echo >&2 "successfully acquired lock"

  # Remove lockdir when the script finishes, or when it receives a signal
  trap "rm -rf $lockdir" 0    # remove directory when script finishes
  trap "exit 2" 1 2 3 15  # terminate script when receiving signal

  # Optionally create temporary files in this directory, because
  # they will be removed automatically:
  tmpfile=$lockdir/filelist
else
  echo >&2 "WARNING - cannot acquire lock, giving up on $lockdir"
  exit 1
fi

# Load openrc if available

if [ -r /root/admin-openrc.sh ]; then
  . /root/admin-openrc.sh
fi

# Load functions

. '/usr/lib/nagios/plugins/check_instance.d/generic.sh'
. '/usr/lib/nagios/plugins/check_instance.d/boot_instance.sh'


# Write out heat template
write_heat_template "${lockdir}/template.yaml" 


# Launch Heat stack

# Check if VM launches.
if spawn_vm "${lockdir}/template.yaml" check_instance_boot_$HOSTNAME; then
  echo "OK - instance launched successfully [heat]"
  show_physical_host_of_vm
  check_network
  retval=$?
  if ((retval)); then
    exit $retval
  else
    cleanup_heat_stack
    exit 0
  fi
else
  echo "CRITICAL: could not create stack [heat]"
  exit 2
fi
